/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;

/**
 *
 * @author Frank
 */
public class CATALOGO extends javax.swing.JFrame {

    /**
     * Creates new form CATALOGO
     */
    public CATALOGO() {
        initComponents();
        configurarEventosMenu();
    }
    
    /**
     * Configura los eventos de los elementos del menú
     */
    private void configurarEventosMenu() {
        // Menú Clientes
        jMenuClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirVentanaClientes();
            }
        });
        
        // Menú Catálogo (ventana actual)
        JmenuCatalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JOptionPane.showMessageDialog(CATALOGO.this, "Ya se encuentra en la sección de Catálogo");
            }
        });
        
        // Menú Inventario
        Jmenuinventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirVentanaInventario();
            }
        });
        
        // Menú Órdenes
        JmenuOrdenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirVentanaOrdenes();
            }
        });
        
        // Menú Facturación
        JmenuFacturacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirVentanaFacturacion();
            }
        });
    }
    
    private void abrirVentanaClientes() {
        try {
            FramePyme ventanaClientes = new FramePyme();
            ventanaClientes.setVisible(true);
            ventanaClientes.setLocationRelativeTo(this);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al abrir Clientes: " + e.getMessage());
        }
    }
    
    private void abrirVentanaInventario() {
        try {
            INVENTARIO ventanaInventario = new INVENTARIO();
            ventanaInventario.setVisible(true);
            ventanaInventario.setLocationRelativeTo(this);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al abrir Inventario: " + e.getMessage());
        }
    }
    
    private void abrirVentanaOrdenes() {
        try {
            ORDENES ventanaOrdenes = new ORDENES();
            ventanaOrdenes.setVisible(true);
            ventanaOrdenes.setLocationRelativeTo(this);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al abrir Órdenes: " + e.getMessage());
        }
    }
    
    private void abrirVentanaFacturacion() {
        try {
            FACTURIZACION ventanaFacturacion = new FACTURIZACION();
            ventanaFacturacion.setVisible(true);
            ventanaFacturacion.setLocationRelativeTo(this);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al abrir Facturación: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableinformacionCatalogo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuClientes = new javax.swing.JMenu();
        JmenuCatalogo = new javax.swing.JMenu();
        Jmenuinventario = new javax.swing.JMenu();
        JmenuOrdenes = new javax.swing.JMenu();
        JmenuFacturacion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableinformacionCatalogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID_PRODUCTO", "NOMBRE PRODUCTO"
            }
        ));
        jScrollPane1.setViewportView(jTableinformacionCatalogo);

        jLabel1.setText("CATALOGO");

        jMenuClientes.setText("CLIENTES");
        jMenuBar1.add(jMenuClientes);

        JmenuCatalogo.setText("CATALOGO");
        jMenuBar1.add(JmenuCatalogo);

        Jmenuinventario.setText("INVENTARIO");
        jMenuBar1.add(Jmenuinventario);

        JmenuOrdenes.setText("ORDENES");
        jMenuBar1.add(JmenuOrdenes);

        JmenuFacturacion.setText("FACTURACION");
        jMenuBar1.add(JmenuFacturacion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CATALOGO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CATALOGO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CATALOGO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CATALOGO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CATALOGO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JmenuCatalogo;
    private javax.swing.JMenu JmenuFacturacion;
    private javax.swing.JMenu JmenuOrdenes;
    private javax.swing.JMenu Jmenuinventario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuClientes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableinformacionCatalogo;
    // End of variables declaration//GEN-END:variables
}
