/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;

/**
 *
 * @author Frank
 */
public class INVENTARIO extends javax.swing.JFrame {

    /**
     * Creates new form INVENTARIO
     */
    public INVENTARIO() {
        initComponents();
        configurarEventosMenu();
    }
    
    /**
     * Configura los eventos de los elementos del menú
     */
    private void configurarEventosMenu() {
        // Menú Clientes
        JmenuClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirVentanaClientes();
            }
        });
        
        // Menú Catálogo
        JmenuCatalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirVentanaCatalogo();
            }
        });
        
        // Menú Inventario (ventana actual)
        JmenuInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JOptionPane.showMessageDialog(INVENTARIO.this, "Ya se encuentra en la sección de Inventario");
            }
        });
        
        // Menú Órdenes
        JmenuOrdenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirVentanaOrdenes();
            }
        });
        
        // Menú Facturación
        JmenuFacturacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirVentanaFacturacion();
            }
        });
    }
    
    private void abrirVentanaClientes() {
        try {
            FramePyme ventanaClientes = new FramePyme();
            ventanaClientes.setVisible(true);
            ventanaClientes.setLocationRelativeTo(this);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al abrir Clientes: " + e.getMessage());
        }
    }
    
    private void abrirVentanaCatalogo() {
        try {
            CATALOGO ventanaCatalogo = new CATALOGO();
            ventanaCatalogo.setVisible(true);
            ventanaCatalogo.setLocationRelativeTo(this);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al abrir Catálogo: " + e.getMessage());
        }
    }
    
    private void abrirVentanaOrdenes() {
        try {
            ORDENES ventanaOrdenes = new ORDENES();
            ventanaOrdenes.setVisible(true);
            ventanaOrdenes.setLocationRelativeTo(this);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al abrir Órdenes: " + e.getMessage());
        }
    }
    
    private void abrirVentanaFacturacion() {
        try {
            FACTURIZACION ventanaFacturacion = new FACTURIZACION();
            ventanaFacturacion.setVisible(true);
            ventanaFacturacion.setLocationRelativeTo(this);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al abrir Facturación: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableInformacionInventario = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        JmenuClientes = new javax.swing.JMenu();
        JmenuCatalogo = new javax.swing.JMenu();
        JmenuInventario = new javax.swing.JMenu();
        JmenuOrdenes = new javax.swing.JMenu();
        JmenuFacturacion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableInformacionInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID_PRODUCTO", "NOMBRE DEL PRODUCTO", "CANTIDAD", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableInformacionInventario);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("INVENTARIO PURAVIDAMIPYMESUITE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        JmenuClientes.setText("CLIENTES");
        jMenuBar1.add(JmenuClientes);

        JmenuCatalogo.setText("CATALOGO");
        jMenuBar1.add(JmenuCatalogo);

        JmenuInventario.setText("INVENTARIO");
        jMenuBar1.add(JmenuInventario);

        JmenuOrdenes.setText("ORDENES");
        jMenuBar1.add(JmenuOrdenes);

        JmenuFacturacion.setText("FACTURACION");
        jMenuBar1.add(JmenuFacturacion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INVENTARIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INVENTARIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INVENTARIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INVENTARIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new INVENTARIO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JmenuCatalogo;
    private javax.swing.JMenu JmenuClientes;
    private javax.swing.JMenu JmenuFacturacion;
    private javax.swing.JMenu JmenuInventario;
    private javax.swing.JMenu JmenuOrdenes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableInformacionInventario;
    // End of variables declaration//GEN-END:variables
}
