/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;

/**
 *
 * @author Frank
 */
public class ORDENES extends javax.swing.JFrame {

    /**
     * Creates new form ORDENES
     */
    public ORDENES() {
        initComponents();
        configurarEventosMenu();
    }
    
    /**
     * Configura los eventos de los elementos del menú
     */
    private void configurarEventosMenu() {
        // Menú Clientes
        jmenuClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirVentanaClientes();
            }
        });
        
        // Menú Catálogo
        Jmenucatalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirVentanaCatalogo();
            }
        });
        
        // Menú Inventario
        jmenuInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirVentanaInventario();
            }
        });
        
        // Menú Órdenes (ventana actual)
        jmenuOrdenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JOptionPane.showMessageDialog(ORDENES.this, "Ya se encuentra en la sección de Órdenes");
            }
        });
        
        // Menú Facturación
        jMenuFacturacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirVentanaFacturacion();
            }
        });
    }
    
    private void abrirVentanaClientes() {
        try {
            FramePyme ventanaClientes = new FramePyme();
            ventanaClientes.setVisible(true);
            ventanaClientes.setLocationRelativeTo(this);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al abrir Clientes: " + e.getMessage());
        }
    }
    
    private void abrirVentanaCatalogo() {
        try {
            CATALOGO ventanaCatalogo = new CATALOGO();
            ventanaCatalogo.setVisible(true);
            ventanaCatalogo.setLocationRelativeTo(this);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al abrir Catálogo: " + e.getMessage());
        }
    }
    
    private void abrirVentanaInventario() {
        try {
            INVENTARIO ventanaInventario = new INVENTARIO();
            ventanaInventario.setVisible(true);
            ventanaInventario.setLocationRelativeTo(this);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al abrir Inventario: " + e.getMessage());
        }
    }
    
    private void abrirVentanaFacturacion() {
        try {
            FACTURIZACION ventanaFacturacion = new FACTURIZACION();
            ventanaFacturacion.setVisible(true);
            ventanaFacturacion.setLocationRelativeTo(this);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al abrir Facturación: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableinformacionFacturacion = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmenuClientes = new javax.swing.JMenu();
        Jmenucatalogo = new javax.swing.JMenu();
        jmenuInventario = new javax.swing.JMenu();
        jmenuOrdenes = new javax.swing.JMenu();
        jMenuFacturacion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jTableinformacionFacturacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID_ORDEN", "ID_PRODUCTO", "ID_CLIENTE", "DIRECCION", "ESTADO DE ORDEN"
            }
        ));
        jScrollPane1.setViewportView(jTableinformacionFacturacion);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graph_marketing_time_strategy_finance_management_business_icon_263055.png"))); // NOI18N
        jLabel1.setText("ORDENES DE PURAVIDAMIPYME");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jmenuClientes.setText("CLIENTES");
        jMenuBar1.add(jmenuClientes);

        Jmenucatalogo.setText("CATALOGO");
        jMenuBar1.add(Jmenucatalogo);

        jmenuInventario.setText("INVENTARIO");
        jMenuBar1.add(jmenuInventario);

        jmenuOrdenes.setText("ORDENES");
        jMenuBar1.add(jmenuOrdenes);

        jMenuFacturacion.setText("FACTURACION");
        jMenuBar1.add(jMenuFacturacion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ORDENES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ORDENES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ORDENES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ORDENES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ORDENES().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Jmenucatalogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFacturacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableinformacionFacturacion;
    private javax.swing.JMenu jmenuClientes;
    private javax.swing.JMenu jmenuInventario;
    private javax.swing.JMenu jmenuOrdenes;
    // End of variables declaration//GEN-END:variables
}
